nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.12.0.cjs

catalog:
  eslint: '^9.39.2'
  prettier: '^3.7.4'
  typescript: '^5.9.3'
  '@poppinss/ts-exec': '^1.4.1'
  '@vinejs/vine': '^4.2.0'
  '@types/node': '^25.0.3'

  # adonisjs
  '@adonisjs/auth': '^10.0.0-next.3'
  '@adonisjs/assembler': '^8.0.0-next.28'
  '@adonisjs/bouncer': '^4.0.0-next.1'
  '@adonisjs/cache': '^2.0.1-next.1'
  '@adonisjs/core': '^7.0.0-next.19'
  '@adonisjs/cors': '^3.0.0-next.0'
  '@adonisjs/eslint-config': '^3.0.0-next.7'
  '@adonisjs/lucid': '^22.0.0-next.4'
  '@adonisjs/session': '^8.0.0-next.2'
  '@adonisjs/tsconfig': '^2.0.0-next.3'
  'youch': '^4.1.0-beta.13'
  'hot-hook': '^0.4.1-next.4'

catalogs:
  adonisjs6:
    '@adonisjs/auth': '^9.5.1'
    '@adonisjs/assembler': '^7.8.2'
    '@adonisjs/bouncer': '^3.1.6'
    '@adonisjs/cache': '^1.3.1'
    '@adonisjs/core': '^6.19.2'
    '@adonisjs/cors': '^2.2.1'
    '@adonisjs/lucid': '^21.8.1'
    '@adonisjs/session': '^7.7.1'
    '@adonisjs/tsconfig': '^1.4.1'
    'youch': '^3.3.5'
    'hot-hook': '^0.4.0'
  adonisjs7:
    '@adonisjs/auth': '^10.0.0-next.3'
    '@adonisjs/assembler': '^8.0.0-next.28'
    '@adonisjs/bouncer': '^4.0.0-next.1'
    '@adonisjs/cache': '^2.0.1-next.1'
    '@adonisjs/core': '^7.0.0-next.19'
    '@adonisjs/cors': '^3.0.0-next.0'
    '@adonisjs/lucid': '^22.0.0-next.4'
    '@adonisjs/session': '^8.0.0-next.2'
    '@adonisjs/tsconfig': '^2.0.0-next.3'
    'youch': '^4.1.0-beta.13'
    'hot-hook': '^0.4.1-next.4'
