import { Secret } from '@adonisjs/core/helpers'
import { GenerateOTPOptions, VerifyOTPOptions } from './types.ts'
import { TokenManager } from '../token/manager.ts'
import { RecordId } from '../../src/types.ts'
import { withOTP, WithOTPOptions } from './main.ts'
import {
  OTP_DEFAULT_EXPIRES_IN,
  OTP_DEFAULT_LENGTH,
  OTP_DEFAULT_MAXIMUM_FAILED_ATTEMPTS,
} from './constants.ts'

/**
 * Config accepted by the OTP manager
 */
export interface OTPManagerConfig {
  /**
   * Number of digits of a code.
   *
   * Defaults to 6
   */
  length?: number

  /**
   * The lifetime of a code, in seconds or as a duration string like
   * "20m".
   *
   * Defaults to "20m"
   */
  expiresIn?: string | number

  /**
   * Number of failed attempts after which a code is invalidated.
   *
   * Defaults to 5
   */
  maximumFailedAttempts?: number
}

/**
 * OTP manager generates and verifies the numeric one-time passwords
 * sent to a user out of band. The codes are hashed with scrypt, since
 * their entropy is too low for a fast hash, and can only be verified
 * against their subject.
 *
 * @example
 * const code = await otp.generateOTP(user.id)
 * await otp.verifyOTP(user.id, code)
 */
export class OTPManager {
  /**
   * The kind under which the codes are persisted
   */
  static TOKEN_KIND = 'otp'

  constructor(
    private config: OTPManagerConfig = {},
    private tokens: TokenManager
  ) {}

  /**
   * Creates a code for a subject and returns it, the only copy of it.
   * Only the hash is persisted.
   *
   * @param tokenableId - The primary key of the subject
   * @param options - Options to configure the code
   */
  async generateOTP(tokenableId: RecordId, options: GenerateOTPOptions = {}) {
    const value = new Secret(
      this.randomOTP(options.length ?? this.config.length ?? OTP_DEFAULT_LENGTH)
    )

    await this.tokens.create(tokenableId, value, {
      kind: OTPManager.TOKEN_KIND,
      purpose: options.purpose,
      expiresIn: options.expiresIn ?? this.config.expiresIn ?? OTP_DEFAULT_EXPIRES_IN,
      maximumFailedAttempts:
        options.maximumFailedAttempts ??
        this.config.maximumFailedAttempts ??
        OTP_DEFAULT_MAXIMUM_FAILED_ATTEMPTS,
      metadata: options.metadata,
      hasher: 'scrypt',
    })

    return value
  }

  /**
   * Verifies a code and consumes it, so that verifying it again
   * fails. A wrong code counts as a failed attempt against every
   * pending code of the subject.
   *
   * @param tokenableId - The primary key of the subject
   * @param value - The code typed by the user
   * @param options - Options to find the code
   *
   * @throws {E_TOO_MANY_ATTEMPTS} When the wrong code reached the
   * maximum failed attempts
   * @throws {E_INVALID_TOKEN} When the code is unknown, expired,
   * already used, or was generated for another purpose
   */
  async verifyOTP(
    tokenableId: RecordId,
    value: Secret<string> | string,
    options: VerifyOTPOptions = {}
  ) {
    return this.tokens.verify(typeof value === 'string' ? new Secret(value) : value, {
      kind: OTPManager.TOKEN_KIND,
      purpose: options.purpose,
      tokenableId,
      hasher: 'scrypt',
    })
  }

  /**
   * Generates a random numeric code of the given length
   */
  protected randomOTP(length: number) {
    if (!Number.isInteger(length) || length < 1) {
      throw new RangeError('length must be a positive integer')
    }

    const bytes = new Uint8Array(length)
    let otp = ''

    while (otp.length < length) {
      crypto.getRandomValues(bytes)
      for (const byte of bytes) {
        /**
         * Skip the bytes from 250 to 255, since 256 is not a
         * multiple of 10 and they would bias the digits
         */
        if (byte >= 250) continue
        otp += byte % 10
        if (otp.length === length) break
      }
    }

    return otp
  }

  /**
   * Mixin to add one-time passwords to a Lucid model. The given
   * options are the defaults of the codes generated by the model.
   * See "withOTP" for the details.
   *
   * @example
   * class User extends compose(BaseModel, otp.withOTP()) {}
   */
  withOTP = (options: WithOTPOptions) => withOTP(this, options)
}
