/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Demo: () => import('#controllers/demo_controller'),
  OpenapiV1: () => import('#controllers/openapi_v1_controller'),
  OpenapiV2: () => import('#controllers/openapi_v2_controller'),
  Posts: () => import('#controllers/posts_controller'),
}
