blank_issues_enabled: true
contact_links:
  - name: 🆘 Need Help?
    url: https://github.com/FriendsOfAdonis/FriendsOfAdonis/discussions
    about: Ask questions and get help from the community
  - name: 📖 Documentation
    url: https://friendsofadonis.com/
    about: Check our documentation for answers