import type { Secret } from '@adonisjs/core/helpers'
import type { NormalizeConstructor } from '@adonisjs/core/types/helpers'
import type { BaseModel } from '@adonisjs/lucid/orm'
import {
  type ManagerReference,
  primaryKeyOf,
  resolveManager,
  staticImplements,
} from '../../../src/helpers.ts'
import otp from '../../../services/otp.ts'
import type { RecordId } from '../../../src/types.ts'
import { E_INVALID_TOKEN } from '../../token/errors.ts'
import type { SentinelToken } from '../../token/token.ts'
import { OTPManager } from '../manager.ts'
import type { GenerateOTPOptions, InvalidateOTPsOptions, VerifyOTPOptions } from '../types.ts'

/**
 * Options accepted by the "withOTP" mixin. The token options are the
 * defaults of the codes generated by the model.
 */
export interface WithOTPOptions extends GenerateOTPOptions {
  /**
   * The manager generating the codes, or a function returning it.
   *
   * Defaults to the OTP service of the application, read on every
   * call. Give one when you construct the manager yourself, in
   * tests for example.
   */
  manager?: ManagerReference<OTPManager>
}

type OTPTokenMetadata = SentinelToken['metadata']

type WithOTPRow = {
  /**
   * Creates a code for the row and returns it. The pending codes of
   * the row for the same purpose are invalidated first.
   */
  generateOTP(options?: GenerateOTPOptions): Promise<Secret<string>>

  /**
   * Invalidates the pending codes of the row. Leaving the purpose
   * out targets the default one of the mixin, or the codes without
   * purpose when the mixin has none.
   */
  invalidateOTPs(options?: InvalidateOTPsOptions): Promise<void>

  /**
   * The manager of the model. See the static getter
   */
  readonly $otpManager: OTPManager
}

type WithOTPClass<
  Model extends NormalizeConstructor<typeof BaseModel> = NormalizeConstructor<typeof BaseModel>,
> = Model & {
  /**
   * Verifies a code and returns the user it was generated for, along
   * with the metadata of the code. The code is consumed, so verifying
   * it again fails.
   *
   * @throws {E_TOO_MANY_ATTEMPTS} When the wrong code reached the
   * maximum failed attempts
   * @throws {E_INVALID_TOKEN} When the code is unknown, expired,
   * already used, was generated for another purpose, or its subject
   * no longer exists
   */
  verifyOTP<T extends WithOTPClass>(
    this: T,
    tokenableId: RecordId,
    value: Secret<string> | string,
    options?: VerifyOTPOptions
  ): Promise<[InstanceType<T>, OTPTokenMetadata]>

  /**
   * The manager generating the codes. It is resolved on every
   * access, from the "manager" option of the mixin or the OTP
   * service of the application. Override it on the model to give
   * it a manager of its own.
   */
  get $otpManager(): OTPManager

  new (...args: any[]): WithOTPRow
}

/**
 * Mixin to add one-time passwords to a model.
 *
 * Under the hood, this mixin defines following methods
 *
 * - generateOTP method to create a code for the row
 * - invalidateOTPs method to revoke the pending codes of the row
 * - verifyOTP static method to find the user a code was generated
 *   for
 * - $otpManager static getter to resolve the manager of the model
 *
 * The manager is resolved on every call, not when the mixin is
 * composed, so the model can be defined before the application
 * has booted.
 *
 * @param options - Options to configure the mixin and the codes
 *
 * @example
 * import { withOTP } from '@foadonis/sentinel/otp'
 *
 * class User extends compose(BaseModel, withOTP({ expiresIn: '5m' })) {}
 */
export function withOTP(options: WithOTPOptions = {}) {
  const { manager, ...defaults } = options

  return function <Model extends NormalizeConstructor<typeof BaseModel>>(
    superclass: Model
  ): WithOTPClass<Model> {
    @staticImplements<WithOTPClass>()
    class WithOTPImpl extends superclass implements WithOTPRow {
      static get $otpManager() {
        return resolveManager(manager, () => otp, 'OTP')
      }

      get $otpManager() {
        return (this.constructor as WithOTPClass).$otpManager
      }

      static async verifyOTP<T extends WithOTPClass>(
        this: T,
        tokenableId: RecordId,
        value: Secret<string> | string,
        options: VerifyOTPOptions = {}
      ): Promise<[InstanceType<T>, OTPTokenMetadata]> {
        /**
         * An explicit undefined purpose must not fall back to the
         * default one
         */
        const purpose = 'purpose' in options ? options.purpose : defaults.purpose
        const token = await this.$otpManager.verifyOTP(tokenableId, value, { purpose })

        const instance = await this.find(token.tokenableId)
        if (!instance) {
          throw new E_INVALID_TOKEN(OTPManager.TOKEN_KIND, purpose)
        }

        return [instance, token.metadata]
      }

      async generateOTP(options: GenerateOTPOptions = {}) {
        return this.$otpManager.generateOTP(primaryKeyOf(this, 'generate an OTP for'), {
          ...defaults,
          ...options,
        })
      }

      async invalidateOTPs(options: InvalidateOTPsOptions = {}) {
        /**
         * An explicit undefined purpose must not fall back to the
         * default one
         */
        const purpose = 'purpose' in options ? options.purpose : defaults.purpose
        return this.$otpManager.invalidateOTPs(primaryKeyOf(this, 'invalidate the OTPs of'), {
          purpose,
        })
      }
    }

    return WithOTPImpl
  }
}
