import { RuntimeException } from '@adonisjs/core/exceptions'
import { Secret } from '@adonisjs/core/helpers'
import string from '@adonisjs/core/helpers/string'
import type { RecordId } from '../../src/types.ts'
import { CRC32 } from '../../src/utils/crc32.ts'
import type { TokenManager } from '../token/manager.ts'
import type { SentinelToken } from '../token/token.ts'
import type {
  GenerateMagicLinkOptions,
  GenerateMagicLinkTokenOptions,
  VerifyMagicLinkTokenOptions,
} from './types.ts'
import { WithMagicLinkOptions } from './main.ts'
import { withMagicLink } from './mixins/with_magic_link.ts'
import { MAGIC_LINK_DEFAULT_EXPIRES_IN } from './constants.ts'

/**
 * Config accepted by the magic link manager
 */
export interface MagicLinkManagerConfig {
  /**
   * The URL the links point to. The token is appended as the "token"
   * query parameter.
   */
  url: string

  /**
   * The lifetime of the links, as a duration string like "20m".
   *
   * Defaults to "20m"
   */
  expiresIn?: string
}

/**
 * Magic link manager generates and verifies the tokens of the
 * passwordless login links.
 *
 * @example
 * const link = await magicLink.generateMagicLink(user.id)
 * await magicLink.verifyMagicLinkToken(token)
 */
export class MagicLinkManager {
  /**
   * The kind under which the tokens are persisted
   */
  static TOKEN_KIND = 'magic_link'

  constructor(
    protected config: MagicLinkManagerConfig,
    protected tokens: TokenManager
  ) {}

  /**
   * Creates a token for a subject and returns the link carrying it.
   * Throws when no URL is configured nor given.
   *
   * @param tokenableId - The primary key of the subject
   * @param options - Options to configure the link and its token
   */
  async generateMagicLink(tokenableId: RecordId, options: GenerateMagicLinkOptions = {}) {
    const base = options.url ?? this.config?.url

    if (!base) {
      throw new RuntimeException(
        'Cannot generate a magic link without a URL. Define "magicLink.url" inside "config/sentinel.ts" or pass the "url" option'
      )
    }

    const url = new URL(base)
    const token = await this.generateMagicLinkToken(tokenableId, options)
    url.searchParams.set('token', token.release())

    return new Secret(url.href)
  }

  /**
   * Creates a token for a subject and returns its value, the only
   * copy of it. Only the hash is persisted.
   *
   * @param tokenableId - The primary key of the subject
   * @param options - Options to configure the token
   */
  async generateMagicLinkToken(tokenableId: RecordId, options: GenerateMagicLinkTokenOptions = {}) {
    /**
     * Suffix the random seed with its checksum, so that secret
     * scanning tools recognize the token
     */
    const seed = string.random(40)
    const value = new Secret(`${seed}${new CRC32().calculate(seed)}`)

    await this.tokens.create(tokenableId, value, {
      kind: MagicLinkManager.TOKEN_KIND,
      purpose: options.purpose,
      expiresIn: options.expiresIn ?? this.config.expiresIn ?? MAGIC_LINK_DEFAULT_EXPIRES_IN,
      metadata: options.metadata,
    })

    return value
  }

  /**
   * Verifies a token and consumes it, so that verifying it again
   * fails.
   *
   * @param value - The value of the token
   * @param options - Options to find the token
   *
   * @throws {E_INVALID_TOKEN} When the token is unknown, expired,
   * already used, or was created for another purpose
   */
  async verifyMagicLinkToken(
    value: Secret<string> | string,
    options: VerifyMagicLinkTokenOptions = {}
  ): Promise<SentinelToken> {
    return this.tokens.verify(typeof value === 'string' ? new Secret(value) : value, {
      kind: MagicLinkManager.TOKEN_KIND,
      purpose: options.purpose,
    })
  }

  /**
   * Mixin to add magic links to a Lucid model. The given options are
   * the defaults of the links generated by the model. See
   * "withMagicLink" for the details.
   *
   * @example
   * class User extends compose(BaseModel, magicLink.withMagicLink({})) {}
   */
  withMagicLink = (options: WithMagicLinkOptions) => withMagicLink(this, options)
}
