import { type Secret } from '@adonisjs/core/helpers'
import type { NormalizeConstructor } from '@adonisjs/core/types/helpers'
import type { BaseModel } from '@adonisjs/lucid/orm'
import {
  type ManagerReference,
  primaryKeyOf,
  resolveManager,
  staticImplements,
} from '../../../src/helpers.ts'
import magicLink from '../../../services/magic_link.ts'
import { E_INVALID_TOKEN } from '../../token/errors.ts'
import type { SentinelToken } from '../../token/token.ts'
import { MagicLinkManager } from '../manager.ts'
import type {
  GenerateMagicLinkOptions,
  GenerateMagicLinkTokenOptions,
  InvalidateMagicLinkTokensOptions,
  VerifyMagicLinkTokenOptions,
} from '../types.ts'

/**
 * Options accepted by the "withMagicLink" mixin. The token options
 * are the defaults of the links generated by the model.
 */
export interface WithMagicLinkOptions extends GenerateMagicLinkOptions {
  /**
   * The manager generating the links, or a function returning it.
   *
   * Defaults to the magic link service of the application, read
   * on every call. Give one when you construct the manager
   * yourself, in tests for example.
   */
  manager?: ManagerReference<MagicLinkManager>
}

type MagicLinkTokenMetadata = SentinelToken['metadata']

type WithMagicLinkRow = {
  /**
   * Creates a token for the row and returns its value
   */
  generateMagicLinkToken(options?: GenerateMagicLinkTokenOptions): Promise<Secret<string>>

  /**
   * Creates a token for the row and returns the link carrying it
   */
  generateMagicLink(options?: GenerateMagicLinkOptions): Promise<Secret<string>>

  /**
   * Invalidates the magic link tokens of the row, so that its
   * pending links stop working. Leaving the purpose out targets the
   * default one of the mixin, or the tokens without purpose when the
   * mixin has none.
   */
  invalidateMagicLinkTokens(options?: InvalidateMagicLinkTokensOptions): Promise<void>

  /**
   * The manager of the model. See the static getter
   */
  readonly $magicLinkManager: MagicLinkManager
}

type WithMagicLinkClass<
  Model extends NormalizeConstructor<typeof BaseModel> = NormalizeConstructor<typeof BaseModel>,
> = Model & {
  /**
   * Verifies a token and returns the user it was created for,
   * along with the metadata of the token. The token is consumed,
   * so verifying it again fails.
   *
   * @throws {E_INVALID_TOKEN} When the token is unknown, expired,
   * already used, was created for another purpose, or its subject
   * no longer exists
   */
  verifyMagicLinkToken<T extends WithMagicLinkClass>(
    this: T,
    value: Secret<string> | string,
    options?: VerifyMagicLinkTokenOptions
  ): Promise<[InstanceType<T>, MagicLinkTokenMetadata]>

  /**
   * The manager generating the links. It is resolved on every
   * access, from the "manager" option of the mixin or the magic
   * link service of the application. Override it on the model to
   * give it a manager of its own.
   */
  get $magicLinkManager(): MagicLinkManager

  new (...args: any[]): WithMagicLinkRow
}

/**
 * Mixin to add magic links to a model.
 *
 * Under the hood, this mixin defines following methods
 *
 * - generateMagicLinkToken and generateMagicLink methods to create a
 *   link for the row
 * - invalidateMagicLinkTokens method to revoke the pending links of
 *   the row
 * - verifyMagicLinkToken static method to find the user a link was
 *   generated for
 * - $magicLinkManager static getter to resolve the manager of the
 *   model
 *
 * The manager is resolved on every call, not when the mixin is
 * composed, so the model can be defined before the application
 * has booted.
 *
 * @param options - Options to configure the mixin and the links
 *
 * @example
 * import { withMagicLink } from '@foadonis/sentinel/magic_link'
 *
 * class User extends compose(
 *   BaseModel,
 *   withMagicLink({ url: (token) => `https://example.com/login/magic?token=${token}` })
 * ) {}
 */
export function withMagicLink(options: WithMagicLinkOptions = {}) {
  const { manager, ...defaults } = options

  return function <Model extends NormalizeConstructor<typeof BaseModel>>(
    superclass: Model
  ): WithMagicLinkClass<Model> {
    @staticImplements<WithMagicLinkClass>()
    class WithMagicLinkImpl extends superclass implements WithMagicLinkRow {
      static get $magicLinkManager() {
        return resolveManager(manager, () => magicLink, 'magic link')
      }

      get $magicLinkManager() {
        return (this.constructor as WithMagicLinkClass).$magicLinkManager
      }

      static async verifyMagicLinkToken<T extends WithMagicLinkClass>(
        this: T,
        value: Secret<string> | string,
        options: VerifyMagicLinkTokenOptions = {}
      ): Promise<[InstanceType<T>, MagicLinkTokenMetadata]> {
        /**
         * An explicit undefined purpose must not fall back to the
         * default one
         */
        const purpose = 'purpose' in options ? options.purpose : defaults.purpose
        const token = await this.$magicLinkManager.verifyMagicLinkToken(value, { purpose })

        const instance = await this.find(token.tokenableId)
        if (!instance) {
          throw new E_INVALID_TOKEN(MagicLinkManager.TOKEN_KIND, purpose)
        }

        return [instance, token.metadata]
      }

      async generateMagicLinkToken(options: GenerateMagicLinkTokenOptions = {}) {
        return this.$magicLinkManager.generateMagicLinkToken(
          primaryKeyOf(this, 'generate a magic link token for'),
          { ...defaults, ...options }
        )
      }

      async generateMagicLink(options: GenerateMagicLinkOptions = {}) {
        return this.$magicLinkManager.generateMagicLink(
          primaryKeyOf(this, 'generate a magic link for'),
          {
            ...defaults,
            ...options,
          }
        )
      }

      async invalidateMagicLinkTokens(options: InvalidateMagicLinkTokensOptions = {}) {
        /**
         * An explicit undefined purpose must not fall back to the
         * default one
         */
        const purpose = 'purpose' in options ? options.purpose : defaults.purpose
        return this.$magicLinkManager.invalidateMagicLinkTokens(
          primaryKeyOf(this, 'invalidate the magic link tokens of'),
          { purpose }
        )
      }
    }

    return WithMagicLinkImpl
  }
}
