import { type Secret } from '@adonisjs/core/helpers'
import type { NormalizeConstructor } from '@adonisjs/core/types/helpers'
import type { BaseModel } from '@adonisjs/lucid/orm'
import { primaryKeyOf, staticImplements } from '../../../src/helpers.ts'
import { E_INVALID_TOKEN } from '../../token/errors.ts'
import type { SentinelToken } from '../../token/token.ts'
import { MagicLinkManager } from '../manager.ts'
import type {
  GenerateMagicLinkOptions,
  GenerateMagicLinkTokenOptions,
  InvalidateMagicLinkTokensOptions,
  VerifyMagicLinkTokenOptions,
} from '../types.ts'

/**
 * Options accepted by the "withMagicLink" mixin. They are the
 * defaults of the links generated by the model.
 */
export interface WithMagicLinkOptions extends GenerateMagicLinkOptions {}

type MagicLinkTokenMetadata = SentinelToken['metadata']

type WithMagicLinkRow = {
  /**
   * Creates a token for the row and returns its value
   */
  generateMagicLinkToken(options?: GenerateMagicLinkTokenOptions): Promise<Secret<string>>

  /**
   * Creates a token for the row and returns the link carrying it
   */
  generateMagicLink(options?: GenerateMagicLinkOptions): Promise<Secret<string>>

  /**
   * Invalidates the magic link tokens of the row, so that its
   * pending links stop working. Leaving the purpose out targets
   * every purpose, the default one of the mixin included.
   */
  invalidateMagicLinkTokens(options?: InvalidateMagicLinkTokensOptions): Promise<void>
}

type WithMagicLinkClass<
  Model extends NormalizeConstructor<typeof BaseModel> = NormalizeConstructor<typeof BaseModel>,
> = Model & {
  /**
   * Verifies a token and returns the user it was created for,
   * along with the metadata of the token. The token is consumed,
   * so verifying it again fails.
   *
   * @throws {E_INVALID_TOKEN} When the token is unknown, expired,
   * already used, was created for another purpose, or its subject
   * no longer exists
   */
  verifyMagicLinkToken<T extends WithMagicLinkClass>(
    this: T,
    value: Secret<string> | string,
    options?: VerifyMagicLinkTokenOptions
  ): Promise<[InstanceType<T>, MagicLinkTokenMetadata]>

  new (...args: any[]): WithMagicLinkRow
}

/**
 * Mixin to add magic links to a model.
 *
 * Under the hood, this mixin defines following methods
 *
 * - generateMagicLinkToken and generateMagicLink methods to create a
 *   link for the row
 * - invalidateMagicLinkTokens method to revoke the pending links of
 *   the row
 * - verifyMagicLinkToken static method to find the user a link was
 *   generated for
 *
 * @param manager - The magic link manager
 * @param defaults - Defaults of the links generated by the model
 *
 * @example
 * class User extends compose(
 *   BaseModel,
 *   withMagicLink(manager, { url: (token) => `https://example.com/login/magic?token=${token}` })
 * ) {}
 */
export function withMagicLink(manager: MagicLinkManager, defaults: WithMagicLinkOptions = {}) {
  return function <Model extends NormalizeConstructor<typeof BaseModel>>(
    superclass: Model
  ): WithMagicLinkClass<Model> {
    @staticImplements<WithMagicLinkClass>()
    class WithMagicLinkImpl extends superclass implements WithMagicLinkRow {
      static async verifyMagicLinkToken<T extends WithMagicLinkClass>(
        this: T,
        value: Secret<string> | string,
        options: VerifyMagicLinkTokenOptions = {}
      ): Promise<[InstanceType<T>, MagicLinkTokenMetadata]> {
        /**
         * An explicit undefined purpose must not fall back to the
         * default one
         */
        const purpose = 'purpose' in options ? options.purpose : defaults.purpose
        const token = await manager.verifyMagicLinkToken(value, { purpose })

        const instance = await this.find(token.tokenableId)
        if (!instance) {
          throw new E_INVALID_TOKEN(MagicLinkManager.TOKEN_KIND, purpose)
        }

        return [instance, token.metadata]
      }

      async generateMagicLinkToken(options: GenerateMagicLinkTokenOptions = {}) {
        return manager.generateMagicLinkToken(
          primaryKeyOf(this, 'generate a magic link token for'),
          { ...defaults, ...options }
        )
      }

      async generateMagicLink(options: GenerateMagicLinkOptions = {}) {
        return manager.generateMagicLink(primaryKeyOf(this, 'generate a magic link for'), {
          ...defaults,
          ...options,
        })
      }

      async invalidateMagicLinkTokens(options: InvalidateMagicLinkTokensOptions = {}) {
        return manager.invalidateMagicLinkTokens(
          primaryKeyOf(this, 'invalidate the magic link tokens of'),
          options
        )
      }
    }

    return WithMagicLinkImpl
  }
}
