import { RuntimeException } from '@adonisjs/core/exceptions'
import type { Secret } from '@adonisjs/core/helpers'
import type { NormalizeConstructor } from '@adonisjs/core/types/helpers'
import { type BaseModel, beforeSave } from '@adonisjs/lucid/orm'
import type { LucidRow } from '@adonisjs/lucid/types/model'
import { DEFAULT_PASSWORD_COLUMN_NAME, DEFAULT_PASSWORD_UIDS } from '../constants.ts'
import { primaryKeyOf, staticImplements } from '../../../src/helpers.ts'
import { E_INVALID_TOKEN } from '../../token/errors.ts'
import type { SentinelToken } from '../../token/token.ts'
import { E_INVALID_CREDENTIALS, E_INVALID_PASSWORD } from '../errors.ts'
import { PasswordManager } from '../manager.ts'
import type {
  GeneratePasswordResetTokenOptions,
  InvalidatePasswordResetTokensOptions,
  VerifyPasswordResetTokenOptions,
} from '../types.ts'

/**
 * Options accepted by the "withPassword" mixin. The token options are
 * the defaults of the reset tokens generated by the model.
 */
export interface WithPasswordOptions extends GeneratePasswordResetTokenOptions {
  /**
   * The columns "verifyCredentials" looks the user up by.
   *
   * Defaults to ["email"]
   */
  uids?: string[]

  /**
   * The column holding the hashed password.
   *
   * Defaults to "password"
   */
  passwordColumnName?: string

  /**
   * Whether a successful "verifyCredentials" rewrites the hashes made
   * with outdated options.
   *
   * Defaults to true
   */
  rehashOnVerify?: boolean
}

type PasswordResetTokenMetadata = SentinelToken['metadata']

type WithPasswordRow = {
  /**
   * Verifies a plain password against the hash of the row
   */
  verifyPassword(plainPassword: string): Promise<boolean>

  /**
   * Verifies a plain password and throws a validation error when
   * it is wrong. The error is shaped like a VineJS failure on the
   * given field, so that the exception handler renders it like
   * any form error.
   *
   * @param plainPassword - The password to verify
   * @param passwordFieldName - The field to report the error on.
   * Defaults to "currentPassword"
   *
   * @throws {E_VALIDATION_ERROR} When the password is wrong
   */
  validatePassword(plainPassword: string, passwordFieldName?: string): Promise<void>

  /**
   * Replaces the password after verifying the current one. The
   * pending reset tokens are invalidated, whatever their purpose.
   *
   * @throws {E_INVALID_PASSWORD} When the current password is
   * wrong
   */
  updatePassword(currentPassword: string, password: string): Promise<void>

  /**
   * Creates a password reset token for the row and returns its
   * value
   */
  generatePasswordResetToken(options?: GeneratePasswordResetTokenOptions): Promise<Secret<string>>

  /**
   * Invalidates the password reset tokens of the row. Leaving the
   * purpose out targets the default one of the mixin, or the
   * tokens without purpose when the mixin has none.
   */
  invalidatePasswordResetTokens(options?: InvalidatePasswordResetTokensOptions): Promise<void>

  /**
   * Returns the hashed password of the row
   */
  getPassword(): string | null
}

type WithPasswordClass<
  Model extends NormalizeConstructor<typeof BaseModel> = NormalizeConstructor<typeof BaseModel>,
> = Model & {
  /**
   * Hashes the password before saving the row, when it has
   * changed
   */
  hashPassword<T extends WithPasswordClass>(this: T, row: InstanceType<T>): Promise<void>

  /**
   * Finds a user by the value of one of the uids
   */
  findForAuth<T extends WithPasswordClass>(
    this: T,
    uids: string[],
    value: string
  ): Promise<InstanceType<T> | null>

  /**
   * Finds a user by uid and verifies its password. An unknown uid
   * and a wrong password fail the same way, so that neither can
   * be told apart.
   *
   * @throws {E_INVALID_CREDENTIALS} When the uid is unknown or
   * the password is wrong
   */
  verifyCredentials<T extends WithPasswordClass>(
    this: T,
    uid: string,
    password: string
  ): Promise<InstanceType<T>>

  /**
   * Verifies a password reset token and returns the user it was
   * created for, along with the metadata of the token. The token
   * is consumed, so verifying it again fails.
   *
   * @throws {E_INVALID_TOKEN} When the token is unknown, expired,
   * already used, was created for another purpose, or its subject
   * no longer exists
   */
  verifyPasswordResetToken<T extends WithPasswordClass>(
    this: T,
    value: Secret<string> | string,
    options?: VerifyPasswordResetTokenOptions
  ): Promise<[InstanceType<T>, PasswordResetTokenMetadata]>

  /**
   * Resets the password of the user a token was created for. The
   * token is consumed and the other pending reset tokens of the
   * user are invalidated, whatever their purpose.
   *
   * @throws {E_INVALID_TOKEN} When the token is unknown, expired,
   * already used, was created for another purpose, or its subject
   * no longer exists
   */
  resetPassword<T extends WithPasswordClass>(
    this: T,
    value: Secret<string> | string,
    password: string,
    options?: VerifyPasswordResetTokenOptions
  ): Promise<[InstanceType<T>, PasswordResetTokenMetadata]>

  new (...args: any[]): WithPasswordRow
}

/**
 * Mixin to add password hashing, verification and reset tokens to a
 * model.
 *
 * Under the hood, this mixin defines following methods and hooks
 *
 * - beforeSave hook to hash the password
 * - findForAuth method to find a user during authentication
 * - verifyCredentials method to verify user credentials and prevent
 *   timing attacks
 * - verifyPassword, validatePassword and updatePassword methods to
 *   work with the current password
 * - generatePasswordResetToken, verifyPasswordResetToken and
 *   resetPassword methods to reset a forgotten password
 *
 * It is a drop-in replacement for "withAuthFinder" from
 * "@adonisjs/auth/mixins/lucid", with the same hook, methods and
 * "E_INVALID_CREDENTIALS" exception. Never compose both, the
 * passwords would be hashed twice. Unlike "withAuthFinder", the
 * hasher is not an argument: the manager brings the default one of
 * "config/hash.ts".
 *
 * @param manager - The password manager
 * @param options - Options to configure the mixin and the reset tokens
 *
 * @example
 * import password from '@foadonis/sentinel/services/password'
 *
 * class User extends compose(
 *   BaseModel,
 *   password.withPassword({ uids: ['email', 'username'] })
 * ) {}
 */
export function withPassword(manager: PasswordManager, options: WithPasswordOptions = {}) {
  const {
    uids = DEFAULT_PASSWORD_UIDS,
    passwordColumnName = DEFAULT_PASSWORD_COLUMN_NAME,
    rehashOnVerify = true,
    ...defaults
  } = options

  return function <Model extends NormalizeConstructor<typeof BaseModel>>(
    superclass: Model
  ): WithPasswordClass<Model> {
    @staticImplements<WithPasswordClass>()
    class WithPasswordImpl extends superclass implements WithPasswordRow {
      @beforeSave()
      static async hashPassword<T extends WithPasswordClass>(this: T, row: InstanceType<T>) {
        if (row.$dirty[passwordColumnName]) {
          ;(row as any)[passwordColumnName] = await manager.hashPassword(
            (row as any)[passwordColumnName]
          )
        }
      }

      static findForAuth<T extends WithPasswordClass>(this: T, uidsList: string[], value: string) {
        const query = this.query()
        uidsList.forEach((uid) => query.orWhere(uid, value))

        return query.limit(1).first() as Promise<InstanceType<T> | null>
      }

      static async verifyCredentials<T extends WithPasswordClass>(
        this: T,
        uid: string,
        password: string
      ): Promise<InstanceType<T>> {
        if (!uid || !password) {
          throw new E_INVALID_CREDENTIALS()
        }

        const row = await this.findForAuth(uids, uid)

        if (!row) {
          /**
           * Hash the password anyway, so that a missing user takes
           * as long as a wrong password
           */
          await manager.hashPassword(password)
          throw new E_INVALID_CREDENTIALS()
        }

        if (!(await row.verifyPassword(password))) {
          throw new E_INVALID_CREDENTIALS()
        }

        const current = row.getPassword()

        if (!current) {
          throw new RuntimeException(
            `Cannot verify password. The value for "${passwordColumnName}" column is undefined or null`
          )
        }

        /**
         * Rewrite the hash when it was made with outdated options
         */
        if (rehashOnVerify && manager.needsRehash(current)) {
          await savePassword(row, passwordColumnName, password)
        }

        return row
      }

      static async verifyPasswordResetToken<T extends WithPasswordClass>(
        this: T,
        value: Secret<string> | string,
        options: VerifyPasswordResetTokenOptions = {}
      ): Promise<[InstanceType<T>, PasswordResetTokenMetadata]> {
        /**
         * An explicit undefined purpose must not fall back to the
         * default one
         */
        const purpose = 'purpose' in options ? options.purpose : defaults.purpose
        const token = await manager.verifyPasswordResetToken(value, { purpose })

        const instance = await this.find(token.tokenableId)
        if (!instance) {
          throw new E_INVALID_TOKEN(PasswordManager.TOKEN_KIND, purpose)
        }

        return [instance, token.metadata]
      }

      static async resetPassword<T extends WithPasswordClass>(
        this: T,
        value: Secret<string> | string,
        password: string,
        options: VerifyPasswordResetTokenOptions = {}
      ): Promise<[InstanceType<T>, PasswordResetTokenMetadata]> {
        const [instance, metadata] = await this.verifyPasswordResetToken(value, options)

        await savePassword(instance, passwordColumnName, password)
        await manager.invalidateAllPasswordResetTokens(
          primaryKeyOf(instance, 'invalidate the password reset tokens of')
        )

        return [instance, metadata]
      }

      verifyPassword(plainPassword: string) {
        const password = this.getPassword()

        if (!password) {
          throw new RuntimeException(
            `Cannot verify password. The value for "${passwordColumnName}" column is undefined or null`
          )
        }

        return manager.verifyPassword(password, plainPassword)
      }

      async validatePassword(plainPassword: string, passwordFieldName?: string) {
        if (!(await this.verifyPassword(plainPassword))) {
          const error = new Error('Validation Error')
          Object.defineProperty(error, 'code', { value: 'E_VALIDATION_ERROR' })
          Object.defineProperty(error, 'status', { value: 422 })
          Object.defineProperty(error, 'messages', {
            value: [
              {
                field: passwordFieldName ?? 'currentPassword',
                message: 'The current password is incorrect',
                rule: 'current_password',
              },
            ],
          })

          throw error
        }
      }

      async updatePassword(currentPassword: string, password: string) {
        if (!(await this.verifyPassword(currentPassword))) {
          throw new E_INVALID_PASSWORD()
        }

        await savePassword(this, passwordColumnName, password)
        await manager.invalidateAllPasswordResetTokens(
          primaryKeyOf(this, 'invalidate the password reset tokens of')
        )
      }

      async generatePasswordResetToken(options: GeneratePasswordResetTokenOptions = {}) {
        return manager.generatePasswordResetToken(
          primaryKeyOf(this, 'generate a password reset token for'),
          { ...defaults, ...options }
        )
      }

      async invalidatePasswordResetTokens(options: InvalidatePasswordResetTokensOptions = {}) {
        /**
         * An explicit undefined purpose must not fall back to the
         * default one
         */
        const purpose = 'purpose' in options ? options.purpose : defaults.purpose
        return manager.invalidatePasswordResetTokens(
          primaryKeyOf(this, 'invalidate the password reset tokens of'),
          { purpose }
        )
      }

      getPassword(): string | null {
        return (
          this.$getAttribute(options.passwordColumnName ?? DEFAULT_PASSWORD_COLUMN_NAME) ?? null
        )
      }
    }

    return WithPasswordImpl
  }
}

/**
 * Saves the plain password on the row. The "beforeSave" hook hashes
 * it.
 */
async function savePassword(instance: LucidRow, passwordColumnName: string, password: string) {
  instance.merge({ [passwordColumnName]: password } as any)
  await instance.save()
}
