import { DateTime } from 'luxon'
import { RuntimeException } from '@adonisjs/core/exceptions'
import type { Secret } from '@adonisjs/core/helpers'
import type { NormalizeConstructor } from '@adonisjs/core/types/helpers'
import type { BaseModel } from '@adonisjs/lucid/orm'
import type { LucidRow, ModelColumnOptions } from '@adonisjs/lucid/types/model'
import {
  type ManagerReference,
  primaryKeyOf,
  resolveManager,
  staticImplements,
} from '../../../src/helpers.ts'
import email from '../../../services/email.ts'
import { E_INVALID_TOKEN } from '../../token/errors.ts'
import type { SentinelToken } from '../../token/token.ts'
import {
  DEFAULT_EMAIL_COLUMN_NAME,
  DEFAULT_EMAIL_VERIFIED_AT_COLUMN_NAME,
  DEFAULT_UNVERIFIED_EMAIL_COLUMN_NAME,
} from '../constants.ts'
import { E_EMAIL_ALREADY_VERIFIED } from '../errors.ts'
import { EmailManager } from '../manager.ts'
import type {
  GenerateEmailVerificationTokenOptions,
  InvalidateEmailVerificationTokensOptions,
  VerifyEmailVerificationTokenOptions,
} from '../types.ts'

/**
 * Options accepted by the "withEmail" mixin. The token options are
 * the defaults of the verification tokens generated by the model.
 */
export interface WithEmailOptions extends GenerateEmailVerificationTokenOptions {
  /**
   * The manager generating the verification tokens, or a function
   * returning it.
   *
   * Defaults to the email service of the application, read on
   * every call. Give one when you construct the manager yourself,
   * in tests for example.
   */
  manager?: ManagerReference<EmailManager>

  /**
   * The column holding the email address.
   *
   * Defaults to "email"
   */
  emailColumnName?: string

  /**
   * The column holding the address awaiting verification.
   *
   * Defaults to "unverifiedEmail"
   */
  unverifiedEmailColumnName?: string

  /**
   * The column holding the timestamp of the verification.
   *
   * Defaults to "emailVerifiedAt"
   */
  emailVerifiedAtColumnName?: string
}

type EmailVerificationTokenMetadata = SentinelToken['metadata']

type WithEmailRow = {
  /**
   * Creates a token verifying the address awaiting verification:
   * the pending address of a change, or the address of the row when
   * it was never verified. Returns the value of the token.
   *
   * @throws {E_EMAIL_ALREADY_VERIFIED} When the email of the row is
   * verified and no change is pending
   */
  generateEmailVerificationToken(
    options?: GenerateEmailVerificationTokenOptions
  ): Promise<Secret<string>>

  /**
   * Requests an email change. A verified address stays in place
   * until the new one is verified, an address never verified is
   * replaced right away, and giving the current verified address
   * back cancels the pending change. The pending verification
   * tokens are invalidated, whatever their purpose.
   */
  changeEmail(email: string): Promise<void>

  /**
   * Invalidates the email verification tokens of the row. Leaving
   * the purpose out targets the default one of the mixin, or the
   * tokens without purpose when the mixin has none.
   */
  invalidateEmailVerificationTokens(
    options?: InvalidateEmailVerificationTokensOptions
  ): Promise<void>

  /**
   * Whether the email of the row has been verified
   */
  readonly hasVerifiedEmail: boolean

  /**
   * The address awaiting verification, or null when no change is
   * pending
   */
  readonly pendingEmail: string | null

  /**
   * The manager of the model. See the static getter
   */
  readonly $emailManager: EmailManager
}

type WithEmailClass<
  Model extends NormalizeConstructor<typeof BaseModel> = NormalizeConstructor<typeof BaseModel>,
> = Model & {
  /**
   * Verifies a token and applies the address it verifies: a pending
   * change becomes the email of the row, and an address never
   * verified is stamped as verified. Returns the row along with the
   * metadata of the token. The token is consumed and the remaining
   * verification tokens of the row are invalidated.
   *
   * @throws {E_INVALID_TOKEN} When the token is unknown, expired,
   * already used, was created for another purpose, its subject no
   * longer exists, or the address it verifies is no longer the one
   * awaiting verification
   */
  verifyEmail<T extends WithEmailClass>(
    this: T,
    value: Secret<string> | string,
    options?: VerifyEmailVerificationTokenOptions
  ): Promise<[InstanceType<T>, EmailVerificationTokenMetadata]>

  /**
   * The manager generating the verification tokens. It is resolved
   * on every access, from the "manager" option of the mixin or the
   * email service of the application. Override it on the model to
   * give it a manager of its own.
   */
  get $emailManager(): EmailManager

  new (...args: any[]): WithEmailRow
}

/**
 * Mixin to add email verification and email changes to a model.
 *
 * Under the hood, this mixin defines following methods
 *
 * - generateEmailVerificationToken method to create a token for the
 *   address awaiting verification
 * - changeEmail method to request, replace or cancel an email change
 * - invalidateEmailVerificationTokens method to revoke the pending
 *   tokens of the row
 * - verifyEmail static method to consume a token and apply the
 *   address it verifies
 * - hasVerifiedEmail and pendingEmail getters to read the state
 * - $emailManager static getter to resolve the manager of the model
 *
 * The model must declare the email column, along with a nullable
 * column for the address awaiting verification and a nullable
 * datetime column for the verification timestamp. The mixin never
 * sends anything: the application emails the token to the address
 * returned by "pendingEmail".
 *
 * The manager is resolved on every call, not when the mixin is
 * composed, so the model can be defined before the application
 * has booted.
 *
 * @param options - Options to configure the mixin and the tokens
 *
 * @example
 * import { withEmail } from '@foadonis/sentinel/email'
 *
 * class User extends compose(BaseModel, withEmail()) {
 *   @column()
 *   declare email: string | null
 *
 *   @column()
 *   declare unverifiedEmail: string | null
 *
 *   @column.dateTime()
 *   declare emailVerifiedAt: DateTime | null
 * }
 */
export function withEmail(options: WithEmailOptions = {}) {
  const {
    manager,
    emailColumnName = DEFAULT_EMAIL_COLUMN_NAME,
    unverifiedEmailColumnName = DEFAULT_UNVERIFIED_EMAIL_COLUMN_NAME,
    emailVerifiedAtColumnName = DEFAULT_EMAIL_VERIFIED_AT_COLUMN_NAME,
    ...defaults
  } = options

  return function <Model extends NormalizeConstructor<typeof BaseModel>>(
    superclass: Model
  ): WithEmailClass<Model> {
    @staticImplements<WithEmailClass>()
    class WithEmailImpl extends superclass implements WithEmailRow {
      static get $emailManager() {
        return resolveManager(manager, () => email, 'email')
      }

      get $emailManager() {
        return (this.constructor as WithEmailClass).$emailManager
      }

      static async verifyEmail<T extends WithEmailClass>(
        this: T,
        value: Secret<string> | string,
        options: VerifyEmailVerificationTokenOptions = {}
      ): Promise<[InstanceType<T>, EmailVerificationTokenMetadata]> {
        /**
         * An explicit undefined purpose must not fall back to the
         * default one
         */
        const purpose = 'purpose' in options ? options.purpose : defaults.purpose
        const invalid = () => new E_INVALID_TOKEN(EmailManager.TOKEN_KIND, purpose)

        const token = await this.$emailManager.verifyEmailVerificationToken(value, { purpose })

        const instance = await this.find(token.tokenableId)
        if (!instance) throw invalid()

        /**
         * The address the token verifies must still be the one
         * awaiting verification, otherwise a token issued before an
         * email change would verify an address no longer on the row
         */
        const address = token.name
        const current = instance.$getAttribute(emailColumnName) ?? null
        const verifiedAt = DateTime.now()

        if (address && address === instance.pendingEmail) {
          /**
           * Promote the pending address. The compare and swap refuses
           * the update when a concurrent change moved the pending
           * address since the row was loaded.
           */
          await compareAndSwap(this, instance, invalid, {
            expect: (query) =>
              query.where(columnOf(this, unverifiedEmailColumnName).columnName, address),
            values: {
              [emailColumnName]: address,
              [unverifiedEmailColumnName]: null,
              [emailVerifiedAtColumnName]: verifiedAt,
            },
          })
        } else if (address && address === current && !instance.hasVerifiedEmail) {
          /**
           * Stamp the address the row signed up with
           */
          await compareAndSwap(this, instance, invalid, {
            expect: (query) =>
              query
                .where(columnOf(this, emailColumnName).columnName, address)
                .whereNull(columnOf(this, emailVerifiedAtColumnName).columnName),
            values: { [emailVerifiedAtColumnName]: verifiedAt },
          })
        } else {
          throw invalid()
        }

        /**
         * The remaining tokens verify addresses of a state that no
         * longer exists
         */
        await this.$emailManager.invalidateAllEmailVerificationTokens(token.tokenableId)

        return [instance, token.metadata]
      }

      async generateEmailVerificationToken(options: GenerateEmailVerificationTokenOptions = {}) {
        const tokenableId = primaryKeyOf(this, 'generate an email verification token for')

        return this.$emailManager.generateEmailVerificationToken(
          tokenableId,
          this.$pendingAddress(),
          { ...defaults, ...options }
        )
      }

      async changeEmail(email: string) {
        const tokenableId = primaryKeyOf(this, 'change the email of')

        if (!email) {
          throw new RuntimeException(
            `Cannot change the email of "${this.constructor.name}": the address is empty`
          )
        }

        /**
         * A merge silently drops the properties that are not columns,
         * so a missing declaration must fail loudly instead
         */
        columnOf(this.constructor as WithEmailClass, emailColumnName)
        columnOf(this.constructor as WithEmailClass, unverifiedEmailColumnName)

        if (!this.hasVerifiedEmail) {
          /**
           * An address never verified holds nothing to preserve, so
           * the typo of a signup is fixed in place
           */
          this.merge({ [emailColumnName]: email, [unverifiedEmailColumnName]: null } as any)
        } else if (email === this.$getAttribute(emailColumnName)) {
          /**
           * Giving the verified address back cancels the pending
           * change without asking to verify it again
           */
          this.merge({ [unverifiedEmailColumnName]: null } as any)
        } else {
          this.merge({ [unverifiedEmailColumnName]: email } as any)
        }

        await this.save()
        await this.$emailManager.invalidateAllEmailVerificationTokens(tokenableId)
      }

      async invalidateEmailVerificationTokens(
        options: InvalidateEmailVerificationTokensOptions = {}
      ) {
        /**
         * An explicit undefined purpose must not fall back to the
         * default one
         */
        const purpose = 'purpose' in options ? options.purpose : defaults.purpose
        return this.$emailManager.invalidateEmailVerificationTokens(
          primaryKeyOf(this, 'invalidate the email verification tokens of'),
          { purpose }
        )
      }

      get hasVerifiedEmail(): boolean {
        const verifiedAt = this.$getAttribute(emailVerifiedAtColumnName)
        return verifiedAt !== null && verifiedAt !== undefined
      }

      get pendingEmail(): string | null {
        return this.$getAttribute(unverifiedEmailColumnName) ?? null
      }

      /**
       * The address awaiting verification: the pending address of a
       * change, or the address of the row when it was never verified
       */
      protected $pendingAddress(): string {
        const pending = this.pendingEmail
        if (pending) return pending

        if (!this.hasVerifiedEmail) {
          const current = this.$getAttribute(emailColumnName)
          if (current) return current

          throw new RuntimeException(
            `Cannot generate an email verification token for "${this.constructor.name}": it has no email address`
          )
        }

        throw new E_EMAIL_ALREADY_VERIFIED()
      }
    }

    return WithEmailImpl
  }

  /**
   * Applies the values on the row with a compare and swap: the update
   * targets the row only while the expected columns still hold, so
   * that a concurrent change fails the verification instead of being
   * overwritten. Throws the given error when the swap lost.
   */
  async function compareAndSwap(
    model: WithEmailClass,
    instance: LucidRow,
    invalid: () => Error,
    swap: {
      expect: (query: ReturnType<WithEmailClass['query']>) => unknown
      values: Record<string, unknown>
    }
  ) {
    const primaryKey = columnOf(model, model.primaryKey)
    const query = model.query().where(primaryKey.columnName, instance.$primaryKeyValue as any)

    swap.expect(query as ReturnType<WithEmailClass['query']>)

    const result = await query.update(
      Object.fromEntries(
        Object.entries(swap.values).map(([property, value]) => {
          const column = columnOf(model, property)
          return [
            column.columnName,
            value === null ? null : prepare(column, value, property, instance),
          ]
        })
      )
    )

    /**
     * Affected rows are a bare count with some drivers and wrapped
     * in an array with others
     */
    const affected = Array.isArray(result) ? result[0] : result
    if (!affected) throw invalid()

    syncSwappedColumns(instance, swap.values)
  }

  /**
   * Returns the definition of a column of the model, resolved from
   * the property name of the mixin options
   */
  function columnOf(model: WithEmailClass, property: string): ModelColumnOptions {
    const column = model.$getColumn(property)

    if (!column) {
      throw new RuntimeException(
        `The "${property}" property is not a column of the "${model.name}" model. Declare the column or configure the column names of the "withEmail" mixin`
      )
    }

    return column
  }

  /**
   * Serializes a value the way the model would persist it, using the
   * "prepare" function of the column when it defines one
   */
  function prepare(column: ModelColumnOptions, value: unknown, property: string, row: LucidRow) {
    return column.prepare ? column.prepare(value, property, row) : value
  }

  /**
   * Applies the values a compare and swap update just persisted,
   * without leaving the columns dirty. The update wrote them
   * already, so a later "save" must not write them again: it would
   * replay values gone stale over the rows the concurrent instances
   * rewrote since.
   */
  function syncSwappedColumns(row: LucidRow, values: Record<string, unknown>) {
    for (const [property, value] of Object.entries(values)) {
      ;(row as any)[property] = value
      row.$original[property] = value
    }
  }
}
