/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['id', 'tokenableId', 'type', 'name', 'hash', 'abilities', 'createdAt', 'updatedAt', 'lastUsedAt', 'expiresAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column()
  declare name: string | null
  @column()
  declare hash: string
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
}

export class QueueJobSchema extends BaseModel {
  static $columns = ['id', 'queue', 'status', 'data', 'score', 'workerId', 'acquiredAt', 'executeAt', 'finishedAt', 'error'] as const
  $columns = QueueJobSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare queue: string
  @column()
  declare status: string
  @column()
  declare data: string
  @column()
  declare score: bigint | number | null
  @column()
  declare workerId: string | null
  @column()
  declare acquiredAt: bigint | number | null
  @column()
  declare executeAt: bigint | number | null
  @column()
  declare finishedAt: bigint | number | null
  @column()
  declare error: string | null
}

export class QueueScheduleSchema extends BaseModel {
  static $columns = ['id', 'status', 'name', 'payload', 'cronExpression', 'everyMs', 'timezone', 'fromDate', 'toDate', 'runLimit', 'runCount', 'nextRunAt', 'lastRunAt', 'createdAt'] as const
  $columns = QueueScheduleSchema.$columns
  @column({ isPrimary: true })
  declare id: string | null
  @column()
  declare status: string
  @column()
  declare name: string
  @column()
  declare payload: string
  @column()
  declare cronExpression: string | null
  @column()
  declare everyMs: bigint | number | null
  @column()
  declare timezone: string
  @column.dateTime()
  declare fromDate: DateTime | null
  @column.dateTime()
  declare toDate: DateTime | null
  @column()
  declare runLimit: number | null
  @column()
  declare runCount: number
  @column.dateTime()
  declare nextRunAt: DateTime | null
  @column.dateTime()
  declare lastRunAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class RecipeSchema extends BaseModel {
  static $columns = ['id', 'title', 'description', 'ingredients', 'updatedAt', 'createdAt'] as const
  $columns = RecipeSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare title: string | null
  @column()
  declare description: string | null
  @column()
  declare ingredients: any | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['id', 'fullName', 'email', 'password', 'createdAt', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare fullName: string | null
  @column()
  declare email: string
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
