/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { ApiProperty } from '@foadonis/openapi/decorators'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  @ApiProperty({ nullable: false, type: 'string' })
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  @ApiProperty({ nullable: true, type: 'string' })
  declare createdAt: DateTime | null
  @column.dateTime()
  @ApiProperty({ nullable: true, type: 'string' })
  declare expiresAt: DateTime | null
  @column()
  @ApiProperty({ nullable: false, type: 'string' })
  declare hash: string
  @ApiProperty({ nullable: false, type: 'number' })
  declare id: any
  @column.dateTime()
  @ApiProperty({ nullable: true, type: 'string' })
  declare lastUsedAt: DateTime | null
  @column()
  @ApiProperty({ nullable: true, type: 'string' })
  declare name: string | null
  @column()
  @ApiProperty({ nullable: false, type: 'number' })
  declare tokenableId: number
  @column()
  @ApiProperty({ nullable: false, type: 'string' })
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  @ApiProperty({ nullable: true, type: 'string' })
  declare updatedAt: DateTime | null
}

export class RecipeSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'ingredients', 'title', 'updatedAt'] as const
  $columns = RecipeSchema.$columns
  @column.dateTime({ autoCreate: true })
  @ApiProperty({ nullable: true, type: 'string' })
  declare createdAt: DateTime | null
  @column()
  @ApiProperty({ nullable: true, type: 'string' })
  declare description: string | null
  @ApiProperty({ nullable: false, type: 'number' })
  declare id: any
  @column()
  @ApiProperty({ nullable: true, schema: {} })
  declare ingredients: any | null
  @column()
  @ApiProperty({ nullable: true, type: 'string' })
  declare title: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  @ApiProperty({ nullable: true, type: 'string' })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  @ApiProperty({ nullable: false, type: 'string' })
  declare createdAt: DateTime
  @column()
  @ApiProperty({ nullable: false, type: 'string' })
  declare email: string
  @column()
  @ApiProperty({ nullable: true, type: 'string' })
  declare fullName: string | null
  @ApiProperty({ nullable: false, type: 'number' })
  declare id: any
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  @ApiProperty({ nullable: true, type: 'string' })
  declare updatedAt: DateTime | null
}
