import type { RecordId } from '../../src/types.ts'
import type { SentinelToken } from './token.ts'

/**
 * Strategies available for hashing token values before persisting them.
 * Only the hash is stored, the value itself is handed once to the user.
 *
 * - `sha256`: fast and deterministic. The right choice for high-entropy
 *   secrets generated by the package (magic links, verification links).
 *   Tokens can be looked up by their value.
 * - `scrypt`: slow and salted, backed by the `scrypt` hasher of the
 *   application hash service. The right choice for low-entropy secrets
 *   typed by a human (one-time passwords). Tokens can only be looked up
 *   by their tokenable.
 */
export type TokenHasher = 'sha256' | 'scrypt'

export interface TokenHasherContract {
  /**
   * Whether the same value always produces the same hash.
   * Deterministic hashers allow looking tokens up by their hash.
   */
  readonly deterministic: boolean

  /**
   * Hashes a token value for persistence.
   */
  make(value: string): Promise<string>

  /**
   * Verifies a token value against a persisted hash.
   */
  verify(hash: string, value: string): Promise<boolean>
}

export interface CreateTokenOptions {
  /**
   * Kind of tokens created.
   *
   * @example "magic_link"
   */
  kind: string

  /**
   * Hasher used to persist the token value. Use `scrypt` for
   * low-entropy secrets such as one-time passwords.
   *
   * @default "sha256"
   */
  hasher?: TokenHasher

  /**
   * Number of times this token can be used.
   *
   * @default 1
   */
  maximumUsage?: number

  /**
   * Number of failed verification attempts tolerated before the token
   * is invalidated. Failed attempts are only recorded when verifying by
   * subject (`tokenableId`), a wrong value cannot be matched to a token
   * otherwise. Unlimited by default.
   */
  maximumFailedAttempts?: number

  /**
   * Optional name for identifying the token.
   */
  name?: string

  /**
   * Expiration for the tokens.
   *
   * @default "20m"
   */
  expiresIn?: string | number

  /**
   * Purpose to ensure that the token cannot be used
   * for a different purpose than the one given originally.
   */
  purpose?: string

  /**
   * Additional metadata to be stored with the token.
   */
  metadata?: Record<string, unknown>
}

export interface VerifyTokenOptions {
  /**
   * Kind of the token being verified.
   */
  kind: string

  /**
   * Hasher the token was created with.
   *
   * @default "sha256"
   */
  hasher?: TokenHasher

  /**
   * Purpose the token was created with. A token created with
   * a purpose can only be verified with the same purpose.
   */
  purpose?: string

  /**
   * Identifier of the subject the token belongs to. Narrows the lookup
   * to the tokens of this subject and is required when the hasher is
   * not deterministic (`scrypt`), since such tokens cannot be found
   * by their hash.
   */
  tokenableId?: RecordId
}

export interface InvalidateTokensOptions {
  kind: string

  /**
   * Purpose of the tokens to invalidate. `null` targets tokens without
   * a purpose, leaving it out targets tokens of every purpose.
   */
  purpose?: string | null
}

/**
 * Attributes handed to the provider to persist a token.
 */
export interface TokenAttributes {
  tokenableId: RecordId
  kind: string
  hash: string
  name: string | null
  purpose: string | null
  maximumUsageCount: number
  maximumFailedAttemptsCount: number | null
  metadata: Record<string, unknown> | null
  expiresAt: Date
}

export interface FindTokenOptions {
  kind: string
}

export interface FindTokenableTokensOptions {
  kind: string

  /**
   * Purpose of the tokens to find. `null` targets tokens
   * without a purpose.
   */
  purpose: string | null
}

export interface TokenProviderContract {
  /**
   * Persists a token. The provider only ever sees the hash of the value.
   */
  create(attributes: TokenAttributes): Promise<SentinelToken>

  /**
   * Finds a token from its hash. Only possible for tokens
   * created with a deterministic hasher.
   */
  findByHash(hash: string, options: FindTokenOptions): Promise<SentinelToken | null>

  /**
   * Finds the tokens of a given subject.
   */
  findByTokenableId(
    tokenableId: RecordId,
    options: FindTokenableTokensOptions
  ): Promise<SentinelToken[]>

  /**
   * Atomically increments the usage count of a token, refusing to do so
   * when the token has already reached its maximum usage count.
   *
   * @returns The updated token, or `null` when the token could not be used.
   */
  markAsUsed(token: SentinelToken): Promise<SentinelToken | null>

  /**
   * Atomically increments the failed attempts count of a token, refusing
   * to do so when the token has already reached its maximum failed
   * attempts count.
   *
   * @returns The updated token, or `null` when the token is locked.
   */
  recordFailedAttempt(token: SentinelToken): Promise<SentinelToken | null>

  /**
   * Invalidates a single token.
   */
  invalidate(token: SentinelToken): Promise<void>

  /**
   * Invalidates the tokens of a given subject.
   */
  invalidateByTokenableId(tokenableId: RecordId, options: InvalidateTokensOptions): Promise<void>
}
